### ISSUE TITLE
Error installing DHT

### ISSUE THREAD

**Issue by mshaz** [cflurin/collection#3]
Hi need help with this error. I followed your steps. What cud be wrong here?

pi@raspberrypi:~/.node-red $ sudo npm install node-red-contrib-dht-sensor
-
> node-dht-sensor@0.0.32 preinstall /home/pi/.node-red/node_modules/node-red-contrib-dht-sensor/node_modules/node-dht-sensor
> ./check-lib.sh

Library bcm2835 found.
-
> node-dht-sensor@0.0.32 install /home/pi/.node-red/node_modules/node-red-contrib-dht-sensor/node_modules/node-dht-sensor
> node-gyp configure

> node-dht-sensor@0.0.32 postinstall /home/pi/.node-red/node_modules/node-red-contrib-dht-sensor/node_modules/node-dht-sensor
> node-gyp build

make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-dht-sensor/node_modules/node-dht-sensor/build'
  CXX(target) Release/obj.target/node_dht_sensor/node-dht-sensor.o
In file included from ../node-dht-sensor.cpp:2:0:
../node_modules/nan/nan.h:326:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
node_dht_sensor.target.mk:85: recipe for target 'Release/obj.target/node_dht_sensor/node-dht-sensor.o' failed
make: *** [Release/obj.target/node_dht_sensor/node-dht-sensor.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-dht-sensor/node_modules/node-dht-sensor/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.50+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-contrib-dht-sensor/node_modules/node-dht-sensor
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! node-dht-sensor@0.0.32 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht-sensor@0.0.32 postinstall script.
npm ERR! This is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.50+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-dht-sensor"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0

**Comment by cflurin** [comment]
Hi,
node v0.10.29 and npm v1.4.21 are quite old!
Which node-red version are you using?

**Comment by mshaz** [comment]
![image](https://user-images.githubusercontent.com/16055146/28934715-82da8b88-78b4-11e7-9bc2-746e497951ba.png)

![image](https://user-images.githubusercontent.com/16055146/28934823-ec087e80-78b4-11e7-9d54-1dfd824f975c.png)


Works like a charm now. Thank you for the solutions. That's my country's temp. Its bit hot here. How do i display the humidity? 

Thank you.

Sorry for the late reply. I was trying to figure out how to install

**Comment by cflurin** [comment]
temperature = msg.payload
humidity = msg.humidity

**Comment by mshaz** [comment]
Using function node after DHT11 node?

**Comment by ycfung** [comment]
I got no errors and everything is well configured, but I can't see the dht node in node-red.
